### ISSUE TITLE
Update CI for recent Kafka versions

### ISSUE THREAD

**Issue by luckyj5** [splunk/kafka-connect-splunk#160] opened 2018-08-09 19:25 UTC
Update CI implementation to support recent Kafka versions: 
- Update docker images per recent Kafka and Kafka connect versions used by Orca Internal performance testing environment.
- Update perf test cases

**Comment by chaitanyaphalak** [comment] 2020-06-03 17:39
Closing as the issue is old, and we actively updating the Kafka versions.

**Closed by chaitanyaphalak** 2020-06-03 17:39 UTC
