### ISSUE TITLE
ConcurrentModificationException when removing committed events from KafkaRecordTracker

### ISSUE THREAD

**Issue by jeqo** [splunk/kafka-connect-splunk#261] opened 2020-11-09 12:45 UTC
Currently getting this exception:

```
[2020-10-31 07:52:35,122] ERROR sending batch to splunk encountered error (com.splunk.hecclient.ConcurrentHec:101)
java.util.ConcurrentModificationException
	at java.util.TreeMap$PrivateEntryIterator.remove(TreeMap.java:1232)
	at com.splunk.kafka.connect.KafkaRecordTracker.removeAckedEventBatch(KafkaRecordTracker.java:72)
	at com.splunk.kafka.connect.KafkaRecordTracker.removeAckedEventBatches(KafkaRecordTracker.java:49)
	at com.splunk.kafka.connect.SplunkSinkTask.onEventCommitted(SplunkSinkTask.java:350)
	at com.splunk.hecclient.ResponsePoller.add(ResponsePoller.java:82)
	at com.splunk.hecclient.Indexer.send(Indexer.java:137)
	at com.splunk.hecclient.HecChannel.send(HecChannel.java:61)
	at com.splunk.hecclient.LoadBalancer.send(LoadBalancer.java:106)
	at com.splunk.hecclient.Hec.send(Hec.java:234)
	at com.splunk.hecclient.ConcurrentHec.send(ConcurrentHec.java:97)
	at com.splunk.hecclient.ConcurrentHec.run(ConcurrentHec.java:89)
	at com.splunk.hecclient.ConcurrentHec.lambda$new$1(ConcurrentHec.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

KafkaRecordTracker keeps concurrent hash map of `<TopicPartition -> TreeMap<Long -> EventBatch>>`. ConcurrentHashMap doc [1] specifies:

> [...] However, even though all operations are thread-safe, retrieval operations do not entail locking, and there is not any support for locking the entire table in a way that prevents all access.  [...]

If I'm reading this correctly, once the `TreeMap` is open for put/remove there is no thread safety. 

e.g. removal:

https://github.com/splunk/kafka-connect-splunk/blob/4d8fbe871e945738a806ba47d71105a3aef2ddca/src/main/java/com/splunk/kafka/connect/KafkaRecordTracker.java#L63-L80

and addition here:

https://github.com/splunk/kafka-connect-splunk/blob/4d8fbe871e945738a806ba47d71105a3aef2ddca/src/main/java/com/splunk/kafka/connect/KafkaRecordTracker.java#L100-L101

could happen concurrently, causing the exception above.

---
[1] https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html

**Comment by chaitanyaphalak** [comment] 2020-11-09 18:57
Hey @jeqo this is a duplicate of https://github.com/splunk/kafka-connect-splunk/issues/257
the fix is merged and will be release soon.

**Comment by jeqo** [comment] 2020-11-09 22:33
Thanks @chaitanyaphalak ! 
Do you have any ETA for the next release? and it is safe to use the develop branch in the meantime?

**Comment by chaitanyaphalak** [comment] 2020-11-09 23:27
ETA is probably a day or two. You are free to use develop if you want to but I would recommend waiting for the release.

**Comment by chaitanyaphalak** [comment] 2020-11-10 00:24
Release is out - https://github.com/splunk/kafka-connect-splunk/releases/tag/v2.0.1

**Closed by chaitanyaphalak** 2020-11-10 00:24 UTC
