### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by FranciscoGualdi** [splunk/kafka-connect-splunk#236] opened 2020-07-22 13:14 UTC
The version o the tagged releases are wrong. I downloaded the version 1.2.0 but the version returned by the connect framework is 1.0.0.
`curl localhost:8083/connector-plugins | jq`

  {
    "class": "com.splunk.kafka.connect.SplunkSinkConnector",
    "type": "sink",
    "version": "v1.0.0"
  },

Opening the jar file and see version.properties:
githash=@1e92a95
gitbranch=release/1.0.x
gitversion=v1.0.0

**Comment by mwang2016** [comment] 2020-07-22 17:26
@FranciscoGualdi Thanks for bringing this up, it is a known issue and the fix will be included in the next release.

**Closed** 2020-07-22 17:26 UTC

**Comment by hhromic** [comment] 2021-07-16 13:26
Hello, just noticed that the latest version (current `v2.0.2` also suffers from this issue:
```json
[
  {
    "class": "com.splunk.kafka.connect.SplunkSinkConnector",
    "type": "sink",
    "version": "v2.0.1"
  }
]
```

I think that the problem is that when building the JAR file, the Git repository is not tagged yet to the new version, therefore this snippet bakes the wrong version into the `version.properties` file:

https://github.com/splunk/kafka-connect-splunk/blob/92ef8baf577bac2eb4fb611e313e4458f28d9905/build.sh#L9
